name: Update GitHub Profile Summary Cards

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  generate-profile-summary-cards:
    name: Generate GitHub profile cards
    runs-on: ubuntu-latest

    steps:
      - name: Checkout profile repository
        uses: actions/checkout@v4

      - name: Generate profile summary cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.SUMMARY_GITHUB_TOKEN }}
        with:
          USERNAME: PradnyaPrameswara
          BRANCH_NAME: main
          UTC_OFFSET: 8
          AUTO_PUSH: true
          THEME: tokyonight
          ANIMATION: rise
          DURATION: 2
